Feature/dims
UMCUGenetics/CustomModules pull request #14
Opened 2023-08-29 11:21 UTC by mraves2

Added functionalities for running DIMS pipeline in Nextflow

2023-09-01 07:54 UTC, ellendejong requested changes
Some general notes.

a few comments have examples related to these items
I numbered the items, so you can easily reply if we need to discuss them.
Let's discuss items you disagree on or you think can/should be postponed offline. 

1. I noticed you created a nextflow process for each individual R script. Did you think about possible overhead? Let's discuss this a bit further offline.
2. Try to avoid code duplication whenever possible.
3. I would recommend to use a named argument parser in all R scripts, that supports both optional (named) variables as well as positional (required) parameters. For example with argparse: https://cran.r-project.org/web/packages/argparse/vignettes/argparse.html 
4. is there a code style guide and/or linting you use? I would recommend both
- For example; https://style.tidyverse.org/ or https://google.github.io/styleguide/Rguide.html 
5. Out of curiosity, naming conventions:  any you use by default? Based on current CustomModules repos, i see all processes are UpperCamelCase and python scripts are snake_case. 
6. We are working towards newest Nextflow version for existing pipelines. I see you are using the same nextflow version as current production. Could you consider to use the newest nextflow version? Or, make the workflow compatable with both. Some things I noticed which I believe are incompatible between the nextflow versions:
    - missing parenthesis when including modules; aka include { MakeInit } from './CustomModules/DIMS/MakeInit.nf'
    - val() surrounding variables that are (probably) strings.
7. Consistent use of ${} or $ in all .nf files
8. I miss `tag` in all processes. https://www.nextflow.io/docs/latest/process.html#tag 
9. At some point in most of the R scripts, column or row values are transformed to either character or numeric. I wonder if this can be resolved differently. For example by defining a table with predefined types per column. I think tidyverse's datatable does support mixed types.

2023-09-01 07:54 UTC, ellendejong commented on DIMS/ThermoRawFileParser.nf
> +        mono /hpc/dbg_mz/tools/ThermoRawFileParser_1.1.11/ThermoRawFileParser.exe -i=${raw_file} --output=./
Try not to combine short and long arguments in one process, 
`-i=${raw_file} --output=./`
vs
`--input=${raw_file} --output=./`
or 
`-i=${raw_file} -o=./`

2023-09-01 07:54 UTC, ellendejong commented on DIMS/AverageTechReplicates.nf
> +       path '*_avg.RData', emit: binned
Could you give some examples of output filenames? Could `*` be avoided?
I would recommend to avoid generic filename matching using `*` if possible.

2023-09-01 07:54 UTC, ellendejong commented on DIMS/FillMissing.nf
> +       path(GroupedList_file)
Variable names use both CamelCase and snake_case. Please stick to snake_case format, unless it is an accepted abbreviation, such as mzML file extension. 

In this example:
`GroupedList_file`
vs
`grouped_list_file`

2023-09-01 07:54 UTC, ellendejong commented on DIMS/GenerateBreaks.nf
> +       path 'breaks.fwhm.RData'
Try to use () consistently when defining a variable (either in input or output of processes.)
`path('breaks.fwhm.RData')`

2023-09-01 07:54 UTC, ellendejong commented on DIMS/AddOnFunctions/10-collectSamplesFilled_extraoutput.R
> +.libPaths(new = "/hpc/local/CentOS7/dbg_mz/R_libs/3.2.2")
I know you didn't change this file yet.
Is this safe when running inside the container?
I am a bit worried about that :)

2023-09-01 07:54 UTC, ellendejong commented on DIMS/AddOnFunctions/checkOverlap.R
> +checkOverlap <- function(range1,range2){
Variable and function names should be lowercase. 
mixedCase is allowed only in contexts where that’s already the prevailing style (e.g. threading.py), to retain backwards compatibility.

2023-09-01 07:54 UTC, ellendejong commented on DIMS/FillMissing.R
> +    if (grepl("_neg", peakgrouplist_file)) { scanmode = "negative" }
Seems to be a combination of one liner and not. 
I would prefer:
```
if (grepl("_pos", peakgrouplist_file)) { 
    scanmode = "positive" 
} else {
    if (grepl("_neg", peakgrouplist_file)) {
        scanmode = "negative"
    }
}
```

What does the linting/ style guide recommend?

2023-09-01 07:54 UTC, ellendejong commented on DIMS/FillMissing.R
> +source(paste0(scripts_dir, "AddOnFunctions/ident.hires.noise.HPC.R"))
Could you add comments to describe which variables are loaded?

2023-09-01 07:54 UTC, ellendejong commented on DIMS/FillMissing.R
> +
Try to remove debug print statements and unused (outcommented) code.

2023-09-01 07:54 UTC, ellendejong commented on DIMS/HMDBparts.R
> +              while ((as.numeric(outlist_i[1,column_label]) - as.numeric(outlist_part[min_1_last,column_label]))*1e+06/as.numeric(outlist_i[1,column_label]) < ppm) {
Avoid long lines (> 127 characters).
Is it possible to transform the columns of `outlist_i` to numeric, or define numeric columns when creating the variable?

2023-09-01 07:54 UTC, ellendejong commented on DIMS/HMDBparts_old.R
Remove old and previous versions of R-script.

2023-09-01 07:54 UTC, ellendejong commented on DIMS/PeakGrouping.R
> +        if (dim(tmplist.mass.iso)[1]>0) {
Indentation seems off.

2023-09-01 07:54 UTC, ellendejong commented on DIMS/PeakGroupingIdentified.R
> +    assi_HMDB = iso_HMDB = HMDB_code = NA
Can you explain what happens here?

2023-09-05 07:12 UTC, ellendejong commented on DIMS/AddOnFunctions/run.vbs
Is this file still relevant/used? Several 'personal' file locations, aka:
```
C:\Users\awillem8
C:\Users\mkerkho7
```

2023-09-05 07:26 UTC, ellendejong commented on DIMS/AssignToBins.R
> +  pos_raw_data_matrix[is.na(pos_raw_data_matrix[,"intensity"]), "intensity"] <- 0
Why are NA's replaced with 0? Or maybe more importang, what do NA values in the RAW data mean?

2023-09-05 07:28 UTC, ellendejong commented on DIMS/AssignToBins.R
> +  aggr_int_neg <- stats::aggregate(neg_intensity_above_threshold, list(bin_indices_neg), mean)
If you would use linting in R, it would fix inconsistent use of spaces, for example: 
`which(neg_raw_data_matrix[ ,"intensity"]`
vs
`neg_raw_data_matrix[,"intensity"])`
vs
`raw_data_matrix[pos_index, ] `

2023-10-27 15:32 UTC, rernst requested changes
First, what a lot of work, awesome! Remarks on the nextflow should (and can ) be fixed in my opinion. R stuff is up to you, it is hard to see what is new and what is legacy old code. Refactoring will take up lots of time so you can decide to leave it for now. I would advice to remove the code which is not used anyway (commented out). 

Remarks on nextflow code:
- Add `()` for tuple's: `tuple(val(x), path(y), ...)`
- Add inputs to R script arguments.
- Make sure to let nextflow handle output (do not use things like: `../../../` to put output in a project folder.
- Add DIMS to labels for example: `label 'DIMS_CollectSumAdducts'`
- Replace `$params.scripts_dir` with `${baseDir}`

Remarks on R code:
- Remove commented (dev/debug/old) code.
- Follow coding guideline (https://style.tidyverse.org/syntax.html):
	- variable names -> style and descriptive
	- space usage for lists, calculations, calling functions etc.
	- Maybe use: https://styler.r-lib.org
- Some R files are huge, which makes it very difficult to debug, test and review. 
	- Split using functions.
	- Remove duplicate code -> pos/neg etc.

Some remarks while quickly scanning through AddOnFunctions:
- Merge files based on common functionality, for example all the fit functions.
- Remove code duplication (see first point).
- Rename folder to 'utils' to match other software repo's.

2023-10-27 15:32 UTC, rernst commented on DIMS/AverageTechReplicates.R
> +  n_neg <- 0
This can fit in one line: `sum_neg <- sum_pos <- n_pos <- n_neg <- 0`.

I do not like this for complicated code but for simple variable declarations it is fine.

2023-10-27 15:32 UTC, rernst commented on DIMS/GenerateExcel.R
> +suppressMessages(library("stringr"))
Best practice is to add library loading before any other code.

2023-10-27 15:32 UTC, rernst commented on DIMS/GenerateExcel.R
> +outdir <- "../../../"
Let Nextflow handle output files -> output should be put in work directory and published using nextflow.

2023-10-27 15:32 UTC, rernst commented on DIMS/GenerateExcel.nf
> +       path('AdductSums_*.RData')
Add all the output plots etc.

2023-10-27 15:32 UTC, rernst commented on DIMS/GenerateViolinPlots.R
> +file_expected_biomarkers_IEM <- "/hpc/dbg_mz/tools/db/dIEM/Expected_biomarkers_IEM.csv"
Move to a config or param?

2023-10-27 15:32 UTC, rernst commented on DIMS/HMDBparts_old.R
> +#!/usr/bin/Rscript
Remove this file?

2023-10-27 15:32 UTC, rernst commented on DIMS/PeakFinding.R
> +source(paste0(scripts_dir, "AddOnFunctions/isWithinXppm.R"))
Do you really need all these functions? I don't see a lot being used?

2023-10-27 15:32 UTC, rernst commented on DIMS/PeakGrouping.R
> +          if (dim(tmplist.mass.adduct)[1] > 0) {
combine?

2023-10-27 15:32 UTC, rernst commented on DIMS/PeakGrouping.R
> +          if (dim(tmplist.mass.iso)[1]>0) {
Combine?

2023-10-27 15:32 UTC, rernst commented on DIMS/PeakGrouping.R
> +          if (dim(tmplist.mass.adduct)[1] > 0) {
Combine?

2023-10-27 15:32 UTC, rernst commented on DIMS/UnidentifiedCollectPeaks.R
> +}
Remove?

2023-10-27 15:32 UTC, rernst commented on DIMS/UnidentifiedCollectPeaks.nf
> +       // path('SpectrumPeaks_positive_Unidentified.RData')
Remove?

2023-10-27 15:32 UTC, rernst commented on DIMS/UnidentifiedFillMissing.R
> +  save(peakgrouplist_filled, file=paste0("./", outputfile_name))
Use `outdir`?

2023-10-27 15:32 UTC, rernst commented on DIMS/UnidentifiedFillMissing.R
> +  save(peakgrouplist_filled, file=paste0("./", outputfile_name))
Do you even need to add the `./`?

2023-10-27 15:32 UTC, rernst commented on DIMS/UnidentifiedPeakGrouping.nf
> +        """
Check indentation.

2024-02-29 08:49 UTC, closed without merging