Feature/gender_check_y
UMCUGenetics/CustomModules pull request #17
Opened 2024-02-07 14:17 UTC by melferink

* feature gender_check_y

2024-02-23 12:32 UTC, lvanoijen requested changes
A typo and some remarks for the unit testing.

2024-02-23 12:32 UTC, lvanoijen commented on GenderCheck/test_gendercheck.py
You can use @pytest.mark.parametrize with 1 assert (see examples in DxAutomation) instead of multiple asserts in 1 test. Then not all tests fail/are skipped when 1 fails.

2024-02-23 12:32 UTC, lvanoijen commented on GenderCheck/test_gendercheck.py
> +    assert calculate_gender.is_valid_read(MyObject(20, True, True), 21) is False
Assert 4 looks like an unnecessary test, it is testing the same situation as in assert 1.

2024-02-26 07:07 UTC, melferink commented on ClarityEpp/SampleUDF.nf
> +    // Custom process to run clarity_epp export sample_upd
Too much genetics...too much...

2024-02-26 09:02 UTC, melferink commented on GenderCheck/test_gendercheck.py
Hope this is better now!

2024-02-26 12:24 UTC, lvanoijen approved these changes
Approved

2024-03-01 09:47 UTC, lvanoijen approved these changes

2024-03-05 08:46 UTC, merged