Feature/mosaic hunter
UMCUGenetics/CustomModules pull request #20
Opened 2024-02-14 21:21 UTC by BasMonkey

2024-02-16 09:29 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    tuple(val(sample_id), path(bam_files), path(bai_files))
Generally we use indentation after input/output/script(or shell). I do think this would also improve readability her.

2024-02-16 09:31 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    container = 'docker://umcugenbioinf/mosaic_hunter:1.0.0'
Generally we use the order tag, label, container, shell. I also miss shell here.

2024-02-16 09:32 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    tag = tag {"MosaicHunterQualityCorrection $sample_id"}
tag = tag needed? tag {} should be sufficient

2024-02-16 09:33 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    label = 'MosaicHunterQualityCorrection'
label = needed? label {} should be sufficient

2024-02-16 09:34 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +// Step 1: Process input files
Should this comment be before the process, or within the process?

2024-02-16 09:38 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    SEX_STRING=$(echo "!{sample_id}" | egrep -o '[MF]')
I would prefer spaces surrounding operators. There are multiple in this file

2024-02-16 09:39 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +-C !{mh_config_file_one} \
indentation would be nice for readability

2024-02-16 09:40 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +process MosaicHunterMosaicVariantCalculation {
Many of the previous comment also apply here.

2024-02-16 09:40 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +
Why no comment here about the process?

2024-02-16 14:21 UTC, melferink commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    MosaicHunterQualityCorrection.out
is it possible to remove the .out? Seems odd to me :)

2024-02-16 14:28 UTC, melferink commented on MosaicHunter/1.0.0/exome_lh_ns_sb.conffile
> +input_file=
Move conf to DxNextflowWES repo

2024-02-16 14:28 UTC, melferink commented on MosaicHunter/1.0.0/exome_lh_ns_sb_parameters.conffile
> +xinput_file=
Move conf to DxNextflowWES repo

2024-02-16 14:29 UTC, melferink submitted a review, later dismissed
RE checked Dockerfile (ok)
Changes/question requested .nf script
Move conf files to DxNextflowWES

2024-02-19 08:13 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    tuple(val(sample_id), path(bam_files), path(bai_files))
Fixed the indentation

2024-02-19 08:18 UTC, BasMonkey commented on MosaicHunter/1.0.0/exome_lh_ns_sb_parameters.conffile
> +xinput_file=
Config files are moved to DxNextflowWES

2024-02-19 08:19 UTC, BasMonkey commented on MosaicHunter/1.0.0/exome_lh_ns_sb.conffile
> +input_file=
Config files moved to DxNextflowWES

2024-02-19 08:21 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +-C !{mh_config_file_one} \
I deliberately left out the indentation in order to not get any "strange" / unwanted characters in the command.

2024-02-19 08:24 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +// Step 1: Process input files
Moved to within the process, to match a docstring like style

2024-02-19 08:29 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    tag = tag {"MosaicHunterQualityCorrection $sample_id"}
Refactored the metadata lines

2024-02-19 08:30 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    label = 'MosaicHunterQualityCorrection'
Refactored the metadata lines

2024-02-19 08:47 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    SEX_STRING=$(echo "!{sample_id}" | egrep -o '[MF]')
In Bash, the correct way to declare a variable is without spaces around the = sign. If changed to `SEX_STRING = $(echo "!{sample_id}" | egrep -o '[MF]')`, it would result in an error because Bash would interpret SEX_STRING as a command, and = and everything after it as arguments to that command.

2024-03-12 14:04 UTC, rernst requested changes
Some minor points. Python code looks nice ;)

2024-03-12 14:04 UTC, rernst commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +        MosaicHunterQualityCorrection.out
Does this work?

2024-03-12 14:04 UTC, rernst commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    // Final file, will be renamed to include sample_id and published to output directory
Strictly speaking this is not part of the module code.

2024-03-12 14:46 UTC, BasMonkey commented on GenderCheck/CompareGender.nf
> +    container = 'ghcr.io/umcugenetics/gendercheck_pysam22:1.0.0'
If we need another module like pyvcf, we can easily update the docker file, make a new container and publish it to GitHub Packages with a new (version) tag. I agree on the suggested name change. I'll refactor it to `custommodules_gendercheck:1.0.0`

2024-03-12 14:47 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    // Final file, will be renamed to include sample_id and published to output directory
Which code lines are you referring to?

2024-03-12 14:49 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +            $params.mh_gender_locus_x
Fixed!

2024-03-12 20:47 UTC, rernst commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    // Final file, will be renamed to include sample_id and published to output directory
the comment :)

2024-03-13 14:57 UTC, BasMonkey commented on MosaicHunter/1.0.0/MosaicHunter.nf
> +    // Final file, will be renamed to include sample_id and published to output directory
Removed it :)

2024-03-20 15:43 UTC, rernst approved these changes

2024-03-27 08:49 UTC, merged