Feature/giabeval
UMCUGenetics/CustomModules pull request #21
Opened 2024-02-21 13:57 UTC by ellendejong

### What has changed?

- Created process to edit output of Happy (EditSummaryFileHappy)
- CheckQC will be used to judge output of happy and required a few changes:
    - Select metrics required a regex change to enable parsing all HAPPY outputs. 
    - Merge tables failed when qc_value has floats as strings stored: convert column to float.
    - Added docstrings.

2024-04-12 09:39 UTC, BasMonkey commented on CheckQC/check_qc.py
> +        filename = ".*" + filename
The method `.isalpha()` checks if all the characters in the string filename are alphabetic (a-z, A-Z). This implementation of the check will not work if the given input file string has a non-alphabetic character in it (like a `.` for the file extension, or an `_` in the filename). Thereby it also doesn't work if the file is in a folder, but is still a relative path: using `"Test/File"` as input will still result in `"Test/file"`.

2024-04-12 09:43 UTC, BasMonkey commented on CheckQC/check_qc.py
> +        qc_metric_raw = read_csv(qc_file, comment=qc.get("comment", None), delimiter=qc.get("delim", "\t"), quotechar='"')
Is there no quote char field available in the object? If not, it might still be worth it to add a check / default for it. Makes the script also more fail and futureproof.

2024-04-12 09:46 UTC, BasMonkey commented on CheckQC/check_qc.py
> +        pass
Can you explain why you will try to convert the values to a float, but if it cannot be converted, you still continue? Seems there is no value to converting them

2024-04-12 09:47 UTC, BasMonkey commented on CheckQC/check_qc.py
> +        filename = ".*" + filename
PS There is also no unit test available for this method yet

2024-04-12 09:50 UTC, BasMonkey commented on Utils/VersionLog.nf
>  }
Missing newline at end of file

2024-04-12 09:57 UTC, BasMonkey commented on Utils/create_hsmetrics_summary.py
> +    interval_files_pattern = re.compile("BAIT_INTERVALS=\[(\S*)\].TARGET_INTERVALS=\[(\S*)\]")  # noqa: W605
Maybe add comment explaining why the PEP8 warning is being suppressed here?

2024-04-12 09:58 UTC, BasMonkey requested changes
First of all, I appreciate the docstrings! :D 
Beside the comments I've added to the corresponding lines, a minor remark regarding all files:
- To improve readability, I would suggest to move the description in the dockstring to a new line so it gets separated from the triple quotes. (Like you've already done on line 357 of `CheckQC/check_qc.py`)

2024-04-15 06:16 UTC, ellendejong commented on CheckQC/check_qc.py
> +        filename = ".*" + filename
You are right, quite dangerous. I changed implementation to using `punctuation`.

2024-04-15 08:37 UTC, BasMonkey commented on CheckQC/check_qc.py
> +        pass
Check. I cannot think of another implementation that achieves the same result. For the comments I would suggest to add some background on why the conversion s is needed. Somethin like the fist two sentences of the comment above: 
> Some qc metrics did result in issues / errors when merging the tables...
The merge failed when the column qc_value has floats as strings stored.

2024-04-15 08:49 UTC, BasMonkey approved these changes
All OK!

2024-04-15 09:00 UTC, BasMonkey approved these changes
OK

2024-04-15 09:03 UTC, merged