Feature/giabeval_multiqc
UMCUGenetics/CustomModules pull request #48
Opened 2024-10-03 13:25 UTC by melferink

* Feature GIABEval
* code from https://github.com/UMCUGenetics/CustomModules/tree/feature/giabeval re-commited for minimal changes needed for GIABEval

2024-10-08 10:24 UTC, Jorisvansteenbrugge requested changes
Where are the unit tests?  👀

2024-10-08 10:24 UTC, Jorisvansteenbrugge commented on CheckQC/CheckQC.nf
>          path("${identifier}_summary.csv", emit: qc_output)
Blijkbaar werkte dit, maar het is netter om emit buiten de `path()` te hebben staan
```suggestion
        path("${identifier}_summary.csv"), emit: qc_output
```

2024-10-08 10:24 UTC, Jorisvansteenbrugge commented on CheckQC/check_qc.py
> +    """
As someone that has never seen this function before, this docstring seems incomplete. 
1. What are `QC settings of the metric`? 
2. Metrics is a list of QC files, but is that a QC file for one sample, or are there multiple QC files per sample?
3. What is a joined and judged qc metrics? Maybe you can describe the layout a little bit

2024-10-08 10:24 UTC, Jorisvansteenbrugge commented on CheckQC/check_qc.py
> +            qc_judged_renamed = qc_judged_renamed.astype(object)
Some comments here would be nice to explain what is happening. It seems like you are casting the output(a pandas dataframe) to an `object` type, but what doest that imply/why is it necessary?

2024-10-08 10:24 UTC, Jorisvansteenbrugge commented on Utils/EditSummaryFileHappy.nf
> +        tuple(val(meta), path(summary_csv))
```suggestion
        tuple val(meta), path(summary_csv)
```
To improve readability

2024-10-08 10:24 UTC, Jorisvansteenbrugge commented on Utils/EditSummaryFileHappy.nf
> +        path("${meta.truth}_${meta.query}_SNP_ALL.summary.csv"), emit: snp_all_csv
For future reference, you don't have to specify the complete output paths, this is slightly more flexible if you would change any inputs later on. 
```suggestion
        path("*_INDEL_PASS.summary.csv"), emit: indel_pass_csv
        path("*_INDEL_ALL.summary.csv"), emit: indel_all_csv
        path("*_SNP_PASS.summary.csv"), emit: snp_pass_csv
        path("*_SNP_ALL.summary.csv"), emit: snp_all_csv
```

2024-10-11 09:18 UTC, melferink commented on CheckQC/CheckQC.nf
>          path("${identifier}_summary.csv", emit: qc_output)
Fixed

2024-10-11 09:22 UTC, melferink commented on Utils/EditSummaryFileHappy.nf
> +        path("${meta.truth}_${meta.query}_SNP_ALL.summary.csv"), emit: snp_all_csv
makes sense :)

2024-10-11 12:15 UTC, melferink commented on CheckQC/check_qc.py
> +    """
Renamed params for clarification + updated docstring

2024-10-18 14:15 UTC, Jorisvansteenbrugge commented on CheckQC/check_qc.py
> +            metric_settings["threshold"]
Renaming of the variables and adding the doc strings made this function much clearer!

2024-10-21 08:04 UTC, Jorisvansteenbrugge submitted a review, later dismissed
LGTM

2024-10-22 09:58 UTC, Jorisvansteenbrugge approved these changes
kleine suggestie om een comment wat duidelijker/specifieker te maken

2024-10-22 09:58 UTC, Jorisvansteenbrugge commented on CheckQC/check_qc.py
> +    # If ValueError is raised, probably because qc_value is a string (i.e. PASS/FAIL), continue.
```suggestion
    # qc_value can either be a string (i.e., PASS/FAIL), of a floating point value, depending on the QC metric that was used. Float values need to be cast to float types in the dataframe. For string values a ValueError is raised which can be ignored```

2024-10-22 10:05 UTC, melferink commented on CheckQC/check_qc.py
> +    # If ValueError is raised, probably because qc_value is a string (i.e. PASS/FAIL), continue.
Fair enough

2024-10-22 10:07 UTC, Jorisvansteenbrugge commented on CheckQC/check_qc.py
> +    # For string values a ValueError is raised which can be ignored
Nog beter zo!

2024-10-22 10:07 UTC, Jorisvansteenbrugge approved these changes

2024-10-23 08:14 UTC, merged