Feature/use poetry and remove requirements
UMCUGenetics/CustomModules pull request #49
Opened 2024-10-11 08:33 UTC by ellendejong

### What has changed?

- Requirements.txt removed and instead use poetry exclusively for tools CheckQC, GenderCheck, MosaicHunter.
- Use poetry in Dockerfile.

2024-11-04 09:45 UTC, rernst requested changes
Volgens mij kunnen we voorkomen een dubbele venv te gebruiken? Ook interessant stukje over voorkomen van dependencies bouwen in: https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

2024-11-04 09:45 UTC, rernst commented on CheckQC/Dockerfile
> +	&& $POETRY_VENV/bin/pip3 install poetry==${POETRY_VERSION}
Deze stap snap ik niet, waarom niet poetry 'gewoon' installeren zonder extra venv?

Zie ook: https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

2024-11-11 10:45 UTC, ellendejong commented
> Volgens mij kunnen we voorkomen een dubbele venv te gebruiken? Ook interessant stukje over voorkomen van dependencies bouwen in: https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

Waar verwijs je exact naar?

De `--without dev` kan alleen in dockerfiles, omdat voor de github actions pytest nodig is.

2024-11-11 10:57 UTC, rernst commented on CheckQC/Dockerfile
> +	&& $POETRY_VENV/bin/pip3 install poetry==${POETRY_VERSION}
Right, dat klinkt logisch, ik vond het er dubbel uit zien.

2024-11-11 11:01 UTC, rernst commented
> > Volgens mij kunnen we voorkomen een dubbele venv te gebruiken? Ook interessant stukje over voorkomen van dependencies bouwen in: https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0
> 
> Waar verwijs je exact naar?
> 
> De `--without dev` kan alleen in dockerfiles, omdat voor de github actions pytest nodig is.

Naar '4. Installing dependencies before copying code.' De truuk is volgens mij eerst dependencies installeren en daarna pas t package zelf. Doordat het in 2 stappen is verdeeld kan docker dingen cachen. Anyway behoorlijke optimalisatie stap, kijk maar of je het leuk vindt om in te duiken, mag ook zo door ;).

2024-11-11 11:01 UTC, rernst approved these changes

2024-11-11 11:55 UTC, merged